// Mocks generated by Mockito 5.4.2 from annotations
// in fgitapp/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i11;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fgitapp/common/models/error_model.dart' as _i7;
import 'package:fgitapp/features/users/domain/entity/user_detail_entity.dart'
    as _i8;
import 'package:fgitapp/features/users/domain/entity/user_entity.dart' as _i6;
import 'package:fgitapp/features/users/domain/entity/user_repo_detail_entity.dart'
    as _i9;
import 'package:fgitapp/features/users/domain/repository/user_repositories.dart'
    as _i4;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRepository extends _i1.Mock
    implements _i4.UserDataRepository {
  MockUserDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>>
      getUserDataList() => (super.noSuchMethod(
            Invocation.method(
              #getUserDataList,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>>.value(
                _FakeEither_0<List<_i6.UsersListModel>, _i7.ErrorModel>(
              this,
              Invocation.method(
                #getUserDataList,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>>);

  @override
  _i5.Future<
      _i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>> searchUserDataList(
          dynamic userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUserDataList,
          [userId],
        ),
        returnValue: _i5
            .Future<_i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>>.value(
            _FakeEither_0<List<_i6.UsersListModel>, _i7.ErrorModel>(
          this,
          Invocation.method(
            #searchUserDataList,
            [userId],
          ),
        )),
      ) as _i5.Future<_i2.Either<List<_i6.UsersListModel>, _i7.ErrorModel>>);

  @override
  _i5.Future<_i2.Either<_i8.UserDetailsModel, _i7.ErrorModel>> getUserDetail(
          dynamic loginId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetail,
          [loginId],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i8.UserDetailsModel, _i7.ErrorModel>>.value(
                _FakeEither_0<_i8.UserDetailsModel, _i7.ErrorModel>(
          this,
          Invocation.method(
            #getUserDetail,
            [loginId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i8.UserDetailsModel, _i7.ErrorModel>>);

  @override
  _i5.Future<_i2.Either<List<_i9.RepositoryEntity>, _i7.ErrorModel>>
      getUserRepoDetails(dynamic loginId) => (super.noSuchMethod(
            Invocation.method(
              #getUserRepoDetails,
              [loginId],
            ),
            returnValue: _i5.Future<
                    _i2
                    .Either<List<_i9.RepositoryEntity>, _i7.ErrorModel>>.value(
                _FakeEither_0<List<_i9.RepositoryEntity>, _i7.ErrorModel>(
              this,
              Invocation.method(
                #getUserRepoDetails,
                [loginId],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<List<_i9.RepositoryEntity>, _i7.ErrorModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i11.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i5.Future<_i11.Uint8List>);

  @override
  _i5.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
